# Generated by Django 6.1 on 2026-09-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='brithday',
            new_name='birthday',
        ),
    ]
