# Generated by Django 6.1 on 2026-09-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='realese_date',
            new_name='release_date',
        ),
    ]
